### ISSUE TITLE
Inconsistent bolding and title of blog assignment headers 

### ISSUE THREAD

**Issue by swang96** [joannakl/cs480_s18#114]
Under the "Readings, Assignments, Homework", the header for the blog post assignments are inconsistently bolded. Some appear as "Blog posts for this week:" while others appear as "**Blog posts for this week:**". In addition, some say simply "Blog posts: " instead of "Blog posts for this week:".

**Comment by kellyhogan** [comment]
I can confirm this issue on Google Chrome Version 65.0.3325.181 (Official Build) (64-bit).

There are inconsistencies with "Blog posts" assignment headers for classes 18, 20, 22, and 24:

![image](https://user-images.githubusercontent.com/17225886/39411918-1cd85f4e-4be1-11e8-885d-256271a67e12.png)
![image](https://user-images.githubusercontent.com/17225886/39411958-c4eb5fe2-4be1-11e8-8598-9bc59fc41ff8.png)
![image](https://user-images.githubusercontent.com/17225886/39411917-14a2fbc2-4be1-11e8-8f9e-781a7a4e8b0b.png)
![image](https://user-images.githubusercontent.com/17225886/39411916-0f17563a-4be1-11e8-8b95-a0032c54fded.png)

In addition, class 4 does not even have a header:

![image](https://user-images.githubusercontent.com/17225886/39411969-058e7232-4be2-11e8-9063-9fa60f66e775.png)

Another thing to note is that some classes do not even mention blog posts since they are mentioned on piazza. We should consider not only standardizing blog post headers but also adding in headers and descriptions of blog posts for the classes that do not have them (because they are on piazza).

**Comment by wentaozou1** [comment]
I would like to fix this issue. I will standardize the font for the website as well as the blogpost not the piazza not here.

**Comment by suyasha0** [comment]
I believe week 8 is the blog post description that is missing on the class website. This should be placed under Class # 16.

> - According to the Merrian Webster dictionary, the definition of the word humanitarian (adj) is "relating to or characteristic of people who work to improve the lives and living conditions of other people".   Consider the open source projects that you are familiar with (not necesserily the one that you are working on in this class). Could any of them  be classified as humanitarian  or having humanitarian aspect? Explain. 
> - report on the progress that you group made for your project
> - what is the next thing that you (as an individual) will be working on (as part of your team project)?

**Comment by joannakl** [comment]
There are tons of other inconsistencies like this one. I do not think this is a bug. There is no requirement for these things to be consistent.
