### ISSUE TITLE
Spacing error in bullet point list of topics covered 

### ISSUE THREAD

**Issue by JFernandes1** [joannakl/cs480_s18#20]
On this page: https://joannakl.github.io/cs480_s18/syllabus.html

On Chrome Version 64.0.3282.140

**Comment by swang96** [comment]
More specifically there is an error in spacing between "Case studies of several open source projects" and "Licensing"

**Comment by kellyhogan** [comment]
I can confirm the issue in Google Chrome Version 63.0.3239.132 (Official Build) (64-bit).

The issue seems to be caused by an extra space that has been overlooked due to code that is commented out in lines 63-68 in [syllabus.markdown](https://github.com/joannakl/cs480_s18/blame/gh-pages/syllabus.markdown). Upon closer inspection using the developer tools, I found that there are 2 unordered lists instead of just 1 for "Topics Covered".
![image](https://user-images.githubusercontent.com/17225886/36123676-7051c950-101b-11e8-954e-2fbd167e101b.png)

**Comment by melissaelopez** [comment]
For further clarity, here is what the spacing error looks like on the page currently:
<img width="858" alt="screen shot 2018-02-13 at 12 10 08 pm" src="https://user-images.githubusercontent.com/16906897/36163349-1ea4041e-10b7-11e8-9a03-7cdcfc85b255.png">

**Comment by swang96** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@swang96  go ahead and try to fix this issue, but keep in mind that this html is generated from the markdown text
