### ISSUE TITLE
"How To Get Help" Section: Improper Punctuation and Spacing 

### ISSUE THREAD

**Issue by adnanislam** [joannakl/cs480_s18#24]
On the index page and under the Course Essentials section, "How to Get Help?" should be "How to Get Help:" and the text that follows should start on a new line.

Found on Chrome Version 63.0.3239.132.

**Comment by danagilliann** [comment]
Can confirm with Version 63.0.3239.132
Can be fixed here: https://github.com/joannakl/cs480_s18/blob/126086fb0ff1f9dc4c522528ac522d9ae2963641/index.markdown

**Comment by felixplajer** [comment]
I agree that the text that follows should be on a new line, but I think the question mark instead of a colon is a valid choice (I don't recall how it was before the site-wide mangling). "How to Get Help?" makes just as much sense as "How to Get Help:", since it's more of a question than the other headings in that section.

**Comment by joannakl** [comment]
This can stay as is.

**Comment by adnanislam** [comment]
I'll be closing this issue if it's not in need of fixing, considering it got labeled with a wontfix tag.
