### ISSUE TITLE
Typo in Class #1 section on daily.html

### ISSUE THREAD

**Issue by Matthew-Herman** [joannakl/cs480_s18#32]
Using Chrome 64.0.3282.140 on MacOS 10.12.6

The current lines read as follows:
Producing Open Source Software, , chapter 1
Producing Open Source Software, , chapter 3, IRC section (p. 66)

![commatypodaily](https://user-images.githubusercontent.com/17124331/36064853-8887c640-0e5f-11e8-86ab-5bb9308f4bf4.jpg)

It should probably read as follows:
Producing Open Source Software, chapter 1
Producing Open Source Software, chapter 3, IRC section (p. 66)

**Comment by oekonomi** [comment]
This looks similar to the extra commas in the textbook section mentioned in #14 . They might have the same cause

**Comment by Amethystix** [comment]
Yes, can confirm this error and that it is due to the fact that in the [markdown for this lecture](https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/01.markdown) there is a comma added after the link's name is called as site.book_opt_1, but as you can see [here](https://github.com/joannakl/cs480_s18/blob/78f29bbe02ed584644e2b501dbe7e1a50507663d/_config.yml#L49), the name site.book_opt_1 already has a comma in it, thus generating a double comma.

**Comment by JimenezJC** [comment]
This error also seems to be present on Chromium Version 63.0.3239.132 (Developer Build) (64-bit). 
lad475 seems to have the correct fix, shouldn't be too difficult to implement.

**Comment by Amethystix** [comment]
I'd like to claim this issue!

**Comment by joannakl** [comment]
@lad475  go ahead and work on this issue
