### ISSUE TITLE
Bad link in class number 2

### ISSUE THREAD

**Issue by joannakl** [joannakl/cs480_s18#79]
In class number 2 (which finally appears) the link to 
History of Open Source points to nothing (it simply reloads the current page).

**Comment by gabegordon** [comment]
I'd like to claim this issue.

**Comment by JimenezJC** [comment]
The problem seems to stem from this markdown file.
 https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/02.markdown

If you look at the raw markdown, the link parameter seems to be empty for "History of Open Source"
I'm not entirely sure where this used to link to, if the original link is provided I would like to claim and work on this issue.

**Comment by gabegordon** [comment]
The link should be to https://joannakl.github.io/cs480_s18/slides/week1/history.html.
Issue is fixed in PR #81

**Comment by joannakl** [comment]
@gabegordon  you can work on this
