### ISSUE TITLE
Improperly formatted link in class 2 

### ISSUE THREAD

**Issue by dorasun** [joannakl/cs480_s18#85]
It looks like the link to the github markdown cheatsheet is improperly formatted/broken; problem looks to be in: https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/02.markdown
where there is an extra space in the link

Viewed on the latest version of chrome

**Comment by joannakl** [comment]
can someone confirm it / claim it? 
there are still two people who need a bug assignment

**Comment by ashley-hu** [comment]
Hello, 

I see the issue here: 
![screen shot 2018-02-22 at 10 22 32 pm](https://user-images.githubusercontent.com/19430665/36576479-fafc7798-181e-11e8-9d6f-d1fa9ae9995e.png)

It indeed looks like a markdown issue. According to the markdown cheatsheet, https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links, to create a link in Github, there should be no space between the right bracket and left parenthesis. Deleting the spaces should solve the issue. 

Safari Version 11.0.2 (11604.4.7.1.4).

**Comment by adnanislam** [comment]
I'll claim this

**Comment by sachinsurfs** [comment]
@adnanislam - I am assigning the issue to you. 

-TA
