### ISSUE TITLE
minor typos in class 12 assignment section

### ISSUE THREAD

**Issue by dorasun** [joannakl/cs480_s18#95]
<img width="397" alt="screen shot 2018-03-01 at 10 52 47 pm" src="https://user-images.githubusercontent.com/10905385/36882779-ed196980-1da3-11e8-8bef-e2916c570178.png">

As can be seen in the above screenshot, there are some minor typos under the assignment section of class 12, namely 'assesment' and 'asses' should be 'assess'! 'Strength' is misspelled once as well, and it should be "teammates'" not "team-mates"

Seen on latest version of Chrome

**Comment by PhrydRhys** [comment]
I can verify that this issue is also on Version 64.0.3282.167 (Official Build) (64-bit) of Chrome.

The source of the typos seem to be in the [12.markdown file](https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/12.markdown)

If possible, I would like to claim this issue, regardless if this fix counts as non-trivial or not

**Comment by joannakl** [comment]
thanks for reporting

@PhrydRhys  you can work on this, if still interested
