### ISSUE TITLE
Wrong Instructions for incorporating Contributions document to blog

### ISSUE THREAD

**Issue by ghost** [joannakl/cs480_s18#99]
The instructions for adding the contributions to our personal blogs, under [Class # 18 Thu, 3/29](https://joannakl.github.io/cs480_s18/daily.html), are incorrect. If you perform the instructions as they are, and then click the Contributions link on your blog, you get sent to a 404 Error page. This is because it links to https://nyu-ossd-s18.github.io/cs480_s18/contributions, which doesn't exist, and wouldn't be user-specific anyway.

Identified on Firefox Quantum 59.0.1.

**Comment by oekonomi** [comment]
I managed to add the contribution page to my blog by going into layouts/default.html and inserting 
`<a href="{{site.baseurl}}/contributions">Contributions</a>` below line 31 where the navbar link for the about page is.

**Comment by PhrydRhys** [comment]
I can confirm that using ``<a href="/cs480_s18/contributions">Contributions</a>`` also gave me a 404 error on Chrome Version 64.0.3282.140 (Official Build) (64-bit).

I also can verify that, for my blog, using ``<a href="{{site.baseurl}}/contributions">Contributions</a>`` (as suggested by @oekonomi) worked.

**Comment by dorasun** [comment]
If you look at the source code at [cs480_s18/_includes/daily/18.markdown](https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/18.markdown) it actually does say to use {{site.baseurl}} but I think because of the way the site is formatted, it actually grabbed the baseurl of the site which would be cs480_s18. I think the problem here is that there are spaces inside of the brackets but I can't be sure. 

I think the instructions can be clarified, maybe someone can try getting rid of the spaces in the brackets and seeing if it shows up as `<a href="{{site.baseurl}}/contributions">Contributions</a>` instead of `<a href="/cs480_s18/contributions">Contributions</a>`. I would take this issue but I already made 8 contributions to the course site ;) so I think someone else should do it

**Comment by ckilcrease** [comment]
I'd like to work on this!

**Comment by joannakl** [comment]
@ckilcrease  go for it
